using System;
using System.Collections.Generic;
using System.Text;

namespace Xache.Caching
{
	/// <summary>
	/// Uses a ConcurrentDictionary internally to cache items.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <seealso cref="Xache.Caching.ICachingMethod{TKey, TValue}" />
	/// <autogeneratedoc />
	public class DictionaryCache<TKey, TValue> : ICachingMethod<TKey, TValue>
	{
		public DictionaryCache() => _data = new Dictionary<TKey, TValue>();

		private Dictionary<TKey, TValue> _data;

		public TValue GetOrStore(TKey key, Func<TValue> getValue)
		{
			if (_data.TryGetValue(key, out var value))
			{
				return value;
			}

			value = getValue();

			_data[key] = value;

			return value;
		}
	}
}
