using System;

namespace Xache.Caching
{
	/// <summary>
	/// Generally the function doing the actual work for retrieving a value.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <seealso cref="Xache.Caching.ILastCachingMethod{TKey, TValue}" />
	/// <seealso cref="Xache.Caching.ICachingMethod{TKey, TValue}" />
	/// <autogeneratedoc />
	public class ValueRetrieverCache<TKey, TValue> : ILastCachingMethod<TKey, TValue>
	{
		public ValueRetrieverCache(Func<TKey, TValue> getValue) => _getValue = getValue;

		private readonly Func<TKey, TValue> _getValue;

		[Obsolete("You should use the [" + nameof(GetFrom) + "] method in [" + nameof(ILastCachingMethod<TKey, TValue>) + "] based functions.")]
		public TValue GetOrStore(TKey key, Func<TValue> getValue)
			=> GetFrom(key);

		public TValue GetFrom(TKey key)
			=> _getValue(key);
	}
}