using System;

namespace Xache.Caching
{
	/// <summary>
	/// A mechanism that is used for retrieving values based on keys.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <autogeneratedoc />
	public class CacheMechanism<TKey, TValue>
	{
		public CacheMechanism(Func<TKey, TValue> getValue) => _getValue = getValue;

		private readonly Func<TKey, TValue> _getValue;

		/// <summary>Gets a value for whatever key was specified.</summary>
		/// <param name="key">The key.</param>
		/// <returns></returns>
		/// <autogeneratedoc />
		public TValue Get(TKey key)
			=> _getValue(key);
	}
}