using System;

namespace Xache.Caching
{
	public interface ICachingMethod<TValue>
	{

	}

	/// <summary>
	/// A basic, inheritable, caching method.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <autogeneratedoc />
	public interface ICachingMethod<TKey, TValue> : ICachingMethod<TValue>
	{
		/// <summary>Attempts to get a value based on a key, or if this caching method doesn't have the key, calls upon <paramref name="getValue"/> to get the value and then caches it.</summary>
		/// <param name="key">The key.</param>
		/// <param name="getValue">The get value.</param>
		/// <returns></returns>
		/// <autogeneratedoc />
		TValue GetOrStore(TKey key, Func<TValue> getValue);
	}
}