using System;
using System.Collections.Generic;
using System.Text;

namespace Xache.Caching
{
	/// <summary>
	/// Generally used as the last item in a chain of cachers. This will be the caching method doing the actual work of fetching the value.
	/// </summary>
	/// <typeparam name="TKey">The type of the key.</typeparam>
	/// <typeparam name="TValue">The type of the value.</typeparam>
	/// <seealso cref="Xache.Caching.ICachingMethod{TKey, TValue}" />
	/// <autogeneratedoc />
	public interface ILastCachingMethod<TKey, TValue> : ICachingMethod<TKey, TValue>
	{
		/// <summary>Retrieves the value based upon a key.</summary>
		/// <param name="key">The key.</param>
		/// <returns></returns>
		/// <autogeneratedoc />
		TValue GetFrom(TKey key);
	}
}
